version: '3.3'
services:
  ascent-zipkin:
    image: ascent/ascent-zipkin
    ports:
    - 8700
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker-demo}
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${PLATFORM_TOKEN:-vaultroot}
    networks:
        - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      replicas: ${ZIPKIN_REPLICAS:-1}
      placement:
        constraints:
        - node.role == worker
networks:
 ascentnet:
    external:
      name: ascent_ascentnet
