version: '3.3'
services:
  ascent-zipkin:
    image: ascent/ascent-zipkin:${RELEASE_VERSION:-latest}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker-demo}
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${PLATFORM_TOKEN:-vaultroot}
      - ES_HOST=${ES_HOST:-https://vpc-logging-dev-2q6xjy5atrwwyc7mw7cu3c2uae.us-gov-west-1.es.amazonaws.com}
    networks:
        - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 60s
        monitor: 60s
        failure_action: pause
    ports:
        - "${PORT:-8700:8700}"
    healthcheck:
        test: ["CMD", "/healthcheck", "--url", "https://localhost:8700/actuator/health"]
        interval: 1m
        timeout: 10s
        retries: 3
networks:
 ascentnet:
    external:
      name: ascentnet
