server:
  port: ${zipkin.server.port:8700}
info:
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
logging:
  level:
    org.springframework.cloud.sleuth: INFO
    org.springframework.cloud.sleuth.trace: INFO
    zipkin: WARN
    io.zipkin: WARN

security:
  basic:
    enabled: true
  user:
    name: ${ascent.security.username:admin}
    password: ${ascent.security.password:default}
endpoints:
  health:
    sensitive: false
management.health.rabbit.enabled: false

####################################################################################
# ZIPKIN locally uses in memory span store. Intent is to use ES as storage for Cloud 
# environments which will require configuration similar to what is shown in profile 
# "docker-demo"
#####################################################################################
---
spring:
  profiles: default, local-int
  sleuth:
    stream:
      enabled: false
zipkin:
  sleuth:
    enabled: false
  storage:
      type: mem
security:
  basic:
    enabled: false      
---

spring:
  profiles: docker-demo, aws-ci, aws-stage, aws-prod
zipkin:
  sleuth:
    enabled: false 
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: ${ES_CLUSTER:docker-cluster}
      hosts: ${ES_HOSTS:http://elastic.internal.vets-api.gov:9200}
      index: ${ES_INDEX:zipkin}
      index-shards: ${ES_INDEX_SHARDS:5}
      index-replicas: ${ES_INDEX_REPLICAS:1}
      username: ${zipkin.storage.elasticsearch.username:zipkin}
      password: ${zipkin.storage.elasticsearch.password:changeme}
      

